---
title: "LahmanModeling"
output: html_document
---

```{r, warning=F}
# Libraries
library("DBI")
library("tidyverse")
library("gt")
library("caret")

# Establishing ODBC connection to 'SQLserveR'
con <- dbConnect(odbc::odbc(), "SQLserveR")
```


```{r}
# Classification model - Silver slugger prediction

```


# SQL Query


```{r}
# Notes: 
# - Pull - batting, people, awards from 1980 onward
# - Filter minimum number of At Bats (AB)
# - Create some variables within query
# - Add summarized batting stats
# -
```


```{sql connection=con, output.var = "batting_awards"}
SELECT Batting.*,
       AwardsPlayers.*
FROM lahman2023..Batting
LEFT JOIN lahman2023..AwardsPlayers ON (AwardsPlayers.playerID = Batting.playerID AND AwardsPlayers.yearID = Batting.yearID)
WHERE Batting.yearID >= 1980 
  AND AwardsPlayers.awardID IS NULL OR AwardsPlayers.awardID = 'Silver Slugger'
ORDER BY Batting.yearID
```


```{r}
# Cleaning + Wrangling

# Removing duplicate rows
batting_awards <- batting_awards[,-c(25,27,28)]

# Need to change 'SIlver Slugger' to 'Silver Slugger'
# table(batting_awards$awardID)
batting_awards$awardID <- str_replace_all(batting_awards$awardID, 'I','i')

# Converting 'Sliver Slugger' awardID to 1
batting_awards$awardID <- str_replace_all(batting_awards$awardID, 'Silver Slugger',"1")
batting_awards$awardID <- as.numeric(batting_awards$awardID)

# Removing pitchers for many reasons
batting_awards <- batting_awards %>% filter((!batting_awards$notes %in% ("P")))

# Fixing players with multiple stints having multiple rows by summing numeric columns by playerID/yearID
# Assigning to our more final dataframe
df <- batting_awards %>% group_by(playerID,yearID) %>% summarize(across("G":"awardID", ~ sum(.x, na.rm = TRUE))) %>% ungroup()
```

```{r}
#batting_awards %>% filter(batting_awards$notes != "P")
```



```{r}
# More data checks

# Checking for outright duplicates
#sum(duplicated(df))

# Checking for duplicates of playerID AND yearID
#df %>% group_by(playerID, yearID) %>% filter(row_number(yearID) != 1)

```


# Exploration 


```{r}
# Quickly checking distribution of AB
hist(df$AB)
```


```{r}
# Creating a table of the number of retained observations for each AB cutoff
cutoff <- c(100,200,300,400,500,600)
n_obs <- c(nrow(df[df$AB > 100,]),nrow(df[df$AB > 200,]),nrow(df[df$AB > 300,]),nrow(df[df$AB > 400,]),nrow(df[df$AB > 500,]),nrow(df[df$AB > 600,]))
n_ss <- c(nrow(df[df$AB > 100 & df$awardID > 0,]),nrow(df[df$AB > 200 & df$awardID > 0,]),nrow(df[df$AB > 300 & df$awardID > 0,]),nrow(df[df$AB > 400 & df$awardID > 0,]),nrow(df[df$AB > 500 & df$awardID > 0,]),nrow(df[df$AB > 600 & df$awardID > 0,]))
cut_table <- as.data.frame(cbind(cutoff,n_obs, n_ss))
cut_table <- cut_table %>% mutate(ss_ratio = round((n_ss/n_obs),2), ss_perc = n_ss/(nrow(df[df$awardID > 0,])))

print(cut_table, row.names = FALSE)
```


(TALK ABOUT 2020 SEASON - 1994/1995 shortened seasons)


```{r}
df %>% group_by(playerID,yearID) %>% filter(awardID >= 1 & AB < 200)
```

```{r}
df <- df %>% mutate(PA = (AB + BB + HBP + SF + SH))
#nrow(df)
#nrow(df[df$PA > 502,])

df[df$PA > 502,] %>% summarize(average = mean(AB))

5152/50655
```


A word about J.D. Martinez (2018)














 
# Model Building


```{r}

```


# Confusion Matrix

```{r}

```



# Conclusion

```{r}

```



